### ALL_NBL_Shots

**All coding done in Python3**

**Authored by Eric Nesi**

Just some cleanup of my scraped data.  Continued in workbook entitled "Model NBL Total Data".

In [61]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [62]:
#Read in both player totals and allshots
player_totals = pd.read_csv('/Users/ericnesi/Desktop/capstone_eric/datasets/NBL_Player_Data.csv')
allshots = pd.read_csv('/Users/ericnesi/Desktop/capstone_eric/datasets/All_Shots.csv', index_col=[0])

In [63]:
print(player_totals.head())
print(allshots.head())

          Player                  Team  Games     Min  PTS  FGM  FGA   FG%  \
0     Adam Doyle        Adelaide 36ers     21  134.90   44   15   38  39.5
1    Adam Gibson      Brisbane Bullets     21  613.76  206   70  153  45.8
2  Akil Mitchell  New Zealand Breakers     25  568.47  238  105  189  55.6
3    Aleks Maric          Sydney Kings     28  496.75  150   60  101  59.4
4  Alex Loughton        Cairns Taipans     26  455.83  172   66  145  45.5

   2PM  2PA   2P%  3PM  3PA   3P%  FTM  FTA   FT%  OR   DR   TR  AS  TO  ST  \
0   11   22  50.0    4   16  25.0   10   13  76.9   2    9   11  17  12   4
1   37   73  50.7   33   80  41.3   33   35  94.3  11   43   54  79  33  21
2  103  186  55.4    2    3  66.7   26   79  32.9  49  130  179  53  48  22
3   60  101  59.4    0    0   0.0   30   58  51.7  56   75  131  34  46  32
4   41   84  48.8   25   61  41.0   15   21  71.4  23   54   77  32  17  11

   BL  PFS
0   0   12
1   4   60
2  11   66
3  19   90
4   3   49
  actionType   p  per  perType      player   pno  r  shirtNumber   subType  \
0        2pt   5    1  REGULAR    J. McKay   5.0  0            5  jumpshot
1        2pt  12    1  REGULAR  C. Prather  12.0  0           23  jumpshot
2        2pt   5    1  REGULAR    J. McKay   5.0  1            5  jumpshot
3        2pt  17    1  REGULAR   D. Martin  17.0  1           53  jumpshot
4        2pt   5    1  REGULAR    J. McKay   5.0  1            5  jumpshot

   tno       x       y
0  1.0  10.018  50.680
1  1.0   9.836  56.803
2  1.0   7.104  54.082
3  1.0  10.383  36.395
4  1.0   8.015  56.463

In [64]:
#clean name up
player_totals['First_Init'] = player_totals['Player'].map(lambda x: str(x)[:1])
player_totals[['First_Name','Second_Name', 'Third_Name']]= pd.DataFrame([ x.split() for x in player_totals['Player'].tolist()])

In [65]:
player_totals.head()

,Player,Team,Games,Min,PTS,FGM,FGA,FG%,2PM,2PA,2P%,3PM,3PA,3P%,FTM,FTA,FT%,OR,DR,TR,AS,TO,ST,BL,PFS,First_Init,First_Name,Second_Name,Third_Name
0,Adam Doyle,Adelaide 36ers,21,134.90,44,15,38,39.5,11,22,50.0,4,16,25.0,10,13,76.9,2,9,11,17,12,4,0,12,A,Adam,Doyle,None
1,Adam Gibson,Brisbane Bullets,21,613.76,206,70,153,45.8,37,73,50.7,33,80,41.3,33,35,94.3,11,43,54,79,33,21,4,60,A,Adam,Gibson,None
2,Akil Mitchell,New Zealand Breakers,25,568.47,238,105,189,55.6,103,186,55.4,2,3,66.7,26,79,32.9,49,130,179,53,48,22,11,66,A,Akil,Mitchell,None
3,Aleks Maric,Sydney Kings,28,496.75,150,60,101,59.4,60,101,59.4,0,0,0.0,30,58,51.7,56,75,131,34,46,32,19,90,A,Aleks,Maric,None
4,Alex Loughton,Cairns Taipans,26,455.83,172,66,145,45.5,41,84,48.8,25,61,41.0,15,21,71.4,23,54,77,32,17,11,3,49,A,Alex,Loughton,None

In [66]:
#continue to clean name
player_totals['Third_Name'] = player_totals['Third_Name'].astype(str)
player_totals.loc[player_totals['Third_Name'] == 'None', 'Third_Name'] = ''

In [67]:
player_totals.head(4)

,Player,Team,Games,Min,PTS,FGM,FGA,FG%,2PM,2PA,2P%,3PM,3PA,3P%,FTM,FTA,FT%,OR,DR,TR,AS,TO,ST,BL,PFS,First_Init,First_Name,Second_Name,Third_Name
0,Adam Doyle,Adelaide 36ers,21,134.90,44,15,38,39.5,11,22,50.0,4,16,25.0,10,13,76.9,2,9,11,17,12,4,0,12,A,Adam,Doyle,
1,Adam Gibson,Brisbane Bullets,21,613.76,206,70,153,45.8,37,73,50.7,33,80,41.3,33,35,94.3,11,43,54,79,33,21,4,60,A,Adam,Gibson,
2,Akil Mitchell,New Zealand Breakers,25,568.47,238,105,189,55.6,103,186,55.4,2,3,66.7,26,79,32.9,49,130,179,53,48,22,11,66,A,Akil,Mitchell,
3,Aleks Maric,Sydney Kings,28,496.75,150,60,101,59.4,60,101,59.4,0,0,0.0,30,58,51.7,56,75,131,34,46,32,19,90,A,Aleks,Maric,

In [68]:
#help me to concatenate by replacing none with empty space
player_totals.loc[player_totals['Third_Name'] == None, 'Third_Name'] = ''

In [69]:
player_totals.head()

,Player,Team,Games,Min,PTS,FGM,FGA,FG%,2PM,2PA,2P%,3PM,3PA,3P%,FTM,FTA,FT%,OR,DR,TR,AS,TO,ST,BL,PFS,First_Init,First_Name,Second_Name,Third_Name
0,Adam Doyle,Adelaide 36ers,21,134.90,44,15,38,39.5,11,22,50.0,4,16,25.0,10,13,76.9,2,9,11,17,12,4,0,12,A,Adam,Doyle,
1,Adam Gibson,Brisbane Bullets,21,613.76,206,70,153,45.8,37,73,50.7,33,80,41.3,33,35,94.3,11,43,54,79,33,21,4,60,A,Adam,Gibson,
2,Akil Mitchell,New Zealand Breakers,25,568.47,238,105,189,55.6,103,186,55.4,2,3,66.7,26,79,32.9,49,130,179,53,48,22,11,66,A,Akil,Mitchell,
3,Aleks Maric,Sydney Kings,28,496.75,150,60,101,59.4,60,101,59.4,0,0,0.0,30,58,51.7,56,75,131,34,46,32,19,90,A,Aleks,Maric,
4,Alex Loughton,Cairns Taipans,26,455.83,172,66,145,45.5,41,84,48.8,25,61,41.0,15,21,71.4,23,54,77,32,17,11,3,49,A,Alex,Loughton,

In [70]:
#concatenate all names
player_totals['player'] = player_totals['First_Init'] +'.'+ ' ' + player_totals['Second_Name'] + player_totals['Third_Name']

In [71]:
#drop repeat columns
player_totals = player_totals.drop(['First_Name', 'Player', 'Second_Name', 'Third_Name'], axis=1)

In [72]:
player_totals.head()

,Team,Games,Min,PTS,FGM,FGA,FG%,2PM,2PA,2P%,3PM,3PA,3P%,FTM,FTA,FT%,OR,DR,TR,AS,TO,ST,BL,PFS,First_Init,player
0,Adelaide 36ers,21,134.90,44,15,38,39.5,11,22,50.0,4,16,25.0,10,13,76.9,2,9,11,17,12,4,0,12,A,A. Doyle
1,Brisbane Bullets,21,613.76,206,70,153,45.8,37,73,50.7,33,80,41.3,33,35,94.3,11,43,54,79,33,21,4,60,A,A. Gibson
2,New Zealand Breakers,25,568.47,238,105,189,55.6,103,186,55.4,2,3,66.7,26,79,32.9,49,130,179,53,48,22,11,66,A,A. Mitchell
3,Sydney Kings,28,496.75,150,60,101,59.4,60,101,59.4,0,0,0.0,30,58,51.7,56,75,131,34,46,32,19,90,A,A. Maric
4,Cairns Taipans,26,455.83,172,66,145,45.5,41,84,48.8,25,61,41.0,15,21,71.4,23,54,77,32,17,11,3,49,A,A. Loughton

In [73]:
#make sure name is a str
allshots['player'] = allshots['player'].astype(str)
player_totals['player'] = player_totals['player'].astype(str)

In [74]:
#separate df to merge
player_names = player_totals[['player', 'Team']].copy()

In [75]:
#commence merge
allshots = allshots.merge(player_names, on='player', how='left')

In [76]:
allshots.head()

,actionType,p,per,perType,player,pno,r,shirtNumber,subType,tno,x,y,Team
0,2pt,5,1,REGULAR,J. McKay,5.0,0,5,jumpshot,1.0,10.018,50.680,Perth Wildcats
1,2pt,12,1,REGULAR,C. Prather,12.0,0,23,jumpshot,1.0,9.836,56.803,Perth Wildcats
2,2pt,5,1,REGULAR,J. McKay,5.0,1,5,jumpshot,1.0,7.104,54.082,Perth Wildcats
3,2pt,17,1,REGULAR,D. Martin,17.0,1,53,jumpshot,1.0,10.383,36.395,Perth Wildcats
4,2pt,5,1,REGULAR,J. McKay,5.0,1,5,jumpshot,1.0,8.015,56.463,Perth Wildcats

In [77]:
#lots of nulls
allshots.isnull().sum().sort_values(ascending=False).head(5)

subType    5437
tno        2439
pno        2439
Team         67
y             0
dtype: int64

In [78]:
#rename for column names to match my Kings column names
allshots = allshots.rename(columns={'Team':'Team', 'player':'Player', 'shirtNumber':'PlayerNo', 'x': 'X', 'y':'Y', 'actionType': 'ShotType'})

In [79]:
allshots.head()

,ShotType,p,per,perType,Player,pno,r,PlayerNo,subType,tno,X,Y,Team
0,2pt,5,1,REGULAR,J. McKay,5.0,0,5,jumpshot,1.0,10.018,50.680,Perth Wildcats
1,2pt,12,1,REGULAR,C. Prather,12.0,0,23,jumpshot,1.0,9.836,56.803,Perth Wildcats
2,2pt,5,1,REGULAR,J. McKay,5.0,1,5,jumpshot,1.0,7.104,54.082,Perth Wildcats
3,2pt,17,1,REGULAR,D. Martin,17.0,1,53,jumpshot,1.0,10.383,36.395,Perth Wildcats
4,2pt,5,1,REGULAR,J. McKay,5.0,1,5,jumpshot,1.0,8.015,56.463,Perth Wildcats

In [80]:
#rename continued, reorder
allshots = allshots.rename(columns={'r':'Result', 'subType': 'SubType', 'per': 'Quarter'})
allshots = allshots[['Team', 'Player', 'PlayerNo', 'X', 'Y', 'ShotType', 'SubType', 'Result', 'Quarter']]

In [81]:
allshots.head()

,Team,Player,PlayerNo,X,Y,ShotType,SubType,Result,Quarter
0,Perth Wildcats,J. McKay,5,10.018,50.680,2pt,jumpshot,0,1
1,Perth Wildcats,C. Prather,23,9.836,56.803,2pt,jumpshot,0,1
2,Perth Wildcats,J. McKay,5,7.104,54.082,2pt,jumpshot,1,1
3,Perth Wildcats,D. Martin,53,10.383,36.395,2pt,jumpshot,1,1
4,Perth Wildcats,J. McKay,5,8.015,56.463,2pt,jumpshot,1,1

In [82]:
allshots.head(500)

,Team,Player,PlayerNo,X,Y,ShotType,SubType,Result,Quarter
0,Perth Wildcats,J. McKay,5,10.018,50.680,2pt,jumpshot,0,1
1,Perth Wildcats,C. Prather,23,9.836,56.803,2pt,jumpshot,0,1
2,Perth Wildcats,J. McKay,5,7.104,54.082,2pt,jumpshot,1,1
3,Perth Wildcats,D. Martin,53,10.383,36.395,2pt,jumpshot,1,1
4,Perth Wildcats,J. McKay,5,8.015,56.463,2pt,jumpshot,1,1
5,Perth Wildcats,M. Knight,9,21.858,47.619,2pt,jumpshot,1,1
6,Perth Wildcats,B. Cotton,0,16.576,6.122,3pt,NaN,0,1
7,Perth Wildcats,C. Prather,23,6.375,54.762,2pt,dunk,1,1
8,Perth Wildcats,M. Knight,9,9.107,34.694,2pt,jumpshot,0,1
9,Perth Wildcats,C. Prather,23,6.922,46.259,2pt,layup,1,1
10,Perth Wildcats,B. Cotton,0,26.230,19.728,3pt,NaN,0,1
11,Perth Wildcats,A. Brandt,12,10.565,48.980,2pt,jumpshot,0,1
12,Perth Wildcats,G. Hire,4,5.464,4.082,3pt,NaN,1,1
13,Perth Wildcats,A. Brandt,12,8.743,46.259,2pt,jumpshot,0,1
14,Perth Wildcats,B. Cotton,0,29.872,68.027,3pt,NaN,0,1
15,Perth Wildcats,A. Brandt,12,8.197,48.299,2pt,jumpshot,1,1
16,Perth Wildcats,G. Hire,4,5.647,2.721,3pt,NaN,0,1
17,Perth Wildcats,B. Cotton,0,9.472,50.000,2pt,jumpshot,1,2
18,Perth Wildcats,A. Brandt,12,6.557,35.714,2pt,jumpshot,0,2
19,Perth Wildcats,J. Wagstaff,24,8.015,55.782,2pt,layup,1,2
20,Perth Wildcats,J. Wagstaff,24,7.468,55.442,2pt,layup,1,2
21,Perth Wildcats,B. Cotton,0,27.505,78.571,3pt,NaN,1,2
22,Perth Wildcats,A. Brandt,12,20.947,39.796,2pt,jumpshot,0,2
23,Perth Wildcats,A. Brandt,12,14.026,48.299,2pt,jumpshot,0,2
24,Perth Wildcats,D. Martin,53,31.512,53.401,3pt,NaN,0,2
25,Perth Wildcats,C. Prather,23,19.672,24.490,2pt,jumpshot,0,2
26,Perth Wildcats,S. Redhage,42,31.512,60.884,3pt,NaN,0,2
27,Perth Wildcats,J. McKay,5,6.740,63.946,2pt,layup,1,2
28,Perth Wildcats,S. Redhage,42,10.929,50.680,2pt,jumpshot,0,2
29,Perth Wildcats,C. Prather,23,11.475,95.918,3pt,NaN,0,2
30,Perth Wildcats,J. McKay,5,6.557,40.816,2pt,jumpshot,0,2
31,Perth Wildcats,J. Kenny,8,30.237,68.707,3pt,NaN,0,2
32,Perth Wildcats,J. McKay,5,7.468,55.102,2pt,jumpshot,0,2
33,Perth Wildcats,B. Cotton,0,29.508,74.150,3pt,NaN,1,2
34,Perth Wildcats,B. Cotton,0,8.015,55.442,2pt,layup,1,2
35,Perth Wildcats,M. Knight,9,7.650,50.000,2pt,jumpshot,1,2
36,Perth Wildcats,B. Cotton,0,31.876,65.646,3pt,NaN,0,2
37,Perth Wildcats,C. Prather,23,89.800,40.816,2pt,jumpshot,0,3
38,Perth Wildcats,J. McKay,5,93.807,51.701,2pt,dunk,1,3
39,Perth Wildcats,B. Cotton,0,93.078,51.020,2pt,layup,1,3
40,Perth Wildcats,M. Knight,9,93.807,55.102,2pt,jumpshot,0,3
41,Perth Wildcats,D. Martin,53,93.443,43.878,2pt,jumpshot,0,3
42,Perth Wildcats,M. Knight,9,87.250,53.401,2pt,jumpshot,0,3
43,Perth Wildcats,C. Prather,23,91.803,56.122,2pt,jumpshot,1,3
44,Perth Wildcats,C. Prather,23,72.495,23.129,3pt,NaN,1,3
45,Perth Wildcats,M. Knight,9,93.260,47.279,2pt,jumpshot,0,3
46,Perth Wildcats,C. Prather,23,67.395,52.721,3pt,NaN,0,3
47,Perth Wildcats,J. Wagstaff,24,90.528,41.156,2pt,jumpshot,1,3
48,Perth Wildcats,J. Kenny,8,80.692,24.490,2pt,jumpshot,1,3
49,Perth Wildcats,B. Cotton,0,91.985,44.558,2pt,layup,1,3
50,Perth Wildcats,B. Cotton,0,93.807,76.871,2pt,jumpshot,0,3
51,Perth Wildcats,C. Prather,23,93.625,56.122,2pt,jumpshot,0,3
52,Perth Wildcats,J. Wagstaff,24,89.253,48.639,2pt,jumpshot,0,3
53,Perth Wildcats,J. Wagstaff,24,93.625,54.762,2pt,jumpshot,0,3
54,Perth Wildcats,A. Brandt,12,92.168,54.422,2pt,jumpshot,1,3
55,Perth Wildcats,B. Cotton,0,92.714,51.361,2pt,dunk,1,3
56,Perth Wildcats,J. Kenny,8,75.046,14.966,3pt,NaN,0,3
57,Perth Wildcats,B. Cotton,0,77.960,75.170,2pt,jumpshot,0,3
58,Perth Wildcats,J. Wagstaff,24,91.075,52.381,2pt,jumpshot,0,3
59,Perth Wildcats,J. Wagstaff,24,79.417,49.320,2pt,jumpshot,0,3
60,Perth Wildcats,A. Brandt,12,85.610,65.986,2pt,jumpshot,0,3
61,Perth Wildcats,A. Brandt,12,88.342,62.925,2pt,jumpshot,1,3
62,Perth Wildcats,B. Cotton,0,37.887,15.306,3pt,NaN,0,3
63,Perth Wildcats,M. Knight,9,88.160,52.041,2pt,jumpshot,0,4
64,Perth Wildcats,C. Prather,23,94.353,49.660,2pt,dunk,1,4
65,Perth Wildcats,C. Prather,23,89.253,47.279,2pt,jumpshot,0,4
66,Perth Wildcats,B. Cotton,0,93.625,59.864,2pt,jumpshot,0,4
67,Perth Wildcats,C. Prather,23,89.435,58.503,2pt,jumpshot,0,4
68,Perth Wildcats,C. Prather,23,88.160,41.497,2pt,jumpshot,0,4
69,Perth Wildcats,B. Cotton,0,88.160,60.544,2pt,jumpshot,0,4
70,Perth Wildcats,B. Cotton,0,74.681,86.054,3pt,NaN,0,4
71,Perth Wildcats,D. Martin,53,96.357,3.061,3pt,NaN,0,4
72,Perth Wildcats,B. Cotton,0,91.985,3.061,3pt,NaN,0,4
73,Perth Wildcats,D. Martin,53,95.811,95.918,3pt,NaN,0,4
74,Perth Wildcats,J. Wagstaff,24,76.867,32.653,2pt,jumpshot,1,4
75,Perth Wildcats,B. Cotton,0,92.350,72.789,2pt,jumpshot,0,4
76,Perth Wildcats,J. McKay,5,93.443,55.782,2pt,dunk,1,4
77,Perth Wildcats,J. Kenny,8,93.989,42.517,2pt,jumpshot,0,4
78,Perth Wildcats,J. Kenny,8,92.532,58.163,2pt,layup,1,4
79,Perth Wildcats,J. Kenny,8,93.443,47.959,2pt,jumpshot,0,4
80,Adelaide 36ers,M. Hodgson,1,94.718,53.741,2pt,jumpshot,0,1
81,Adelaide 36ers,T. Ferguson,6,90.346,59.864,2pt,jumpshot,0,1
82,Adelaide 36ers,M. Hodgson,1,95.811,42.177,2pt,dunk,1,1
83,Adelaide 36ers,T. Ferguson,6,96.175,3.741,3pt,NaN,0,1
84,Adelaide 36ers,N. Sobey,20,95.082,22.109,2pt,jumpshot,0,1
85,Adelaide 36ers,N. Sobey,20,89.253,64.626,2pt,jumpshot,0,1
86,Adelaide 36ers,D. Johnson,21,92.896,38.095,2pt,jumpshot,0,1
87,Adelaide 36ers,J. Randle,3,75.774,31.633,2pt,jumpshot,0,1
88,Adelaide 36ers,M. Creek,55,94.718,60.884,2pt,layup,1,1
89,Adelaide 36ers,D. Johnson,21,95.811,96.259,3pt,NaN,0,1
90,Adelaide 36ers,D. Johnson,21,79.235,62.245,2pt,jumpshot,1,1
91,Adelaide 36ers,D. Johnson,21,91.803,37.075,2pt,jumpshot,0,1
92,Adelaide 36ers,A. Drmic,22,92.168,45.238,2pt,layup,1,1
93,Adelaide 36ers,N. Sobey,20,82.332,23.469,2pt,jumpshot,0,1
94,Adelaide 36ers,D. Johnson,21,80.692,89.796,3pt,NaN,0,1
95,Adelaide 36ers,N. Sobey,20,69.945,31.633,3pt,NaN,0,1
96,Adelaide 36ers,B. Teys,7,97.450,3.741,3pt,NaN,0,1
97,Adelaide 36ers,D. Johnson,21,94.171,50.000,2pt,tipin,0,1
98,Adelaide 36ers,N. Sobey,20,48.087,85.714,3pt,NaN,0,1
99,Adelaide 36ers,N. Sobey,20,85.974,28.571,2pt,jumpshot,0,2
100,Adelaide 36ers,N. Sobey,20,90.346,3.401,3pt,NaN,0,2
101,Adelaide 36ers,D. Johnson,21,94.171,50.000,2pt,tipin,1,2
102,Adelaide 36ers,M. Creek,55,76.321,42.177,2pt,jumpshot,0,2
103,Adelaide 36ers,M. Creek,55,90.164,30.272,2pt,jumpshot,1,2
104,Adelaide 36ers,D. Johnson,21,89.800,48.299,2pt,jumpshot,1,2
105,Adelaide 36ers,J. Randle,3,72.131,76.531,3pt,NaN,0,2
106,Adelaide 36ers,J. Randle,3,74.863,39.116,2pt,jumpshot,0,2
107,Adelaide 36ers,J. Randle,3,81.239,63.265,2pt,jumpshot,0,2
108,Adelaide 36ers,J. Randle,3,68.670,64.286,3pt,NaN,1,2
109,Adelaide 36ers,M. Creek,55,89.617,55.102,2pt,jumpshot,1,2
110,Adelaide 36ers,N. Sobey,20,92.168,44.218,2pt,layup,1,2
111,Adelaide 36ers,M. Creek,55,93.807,33.673,2pt,jumpshot,0,2
112,Adelaide 36ers,D. Johnson,21,92.168,55.102,2pt,jumpshot,1,2
113,Adelaide 36ers,A. Drmic,22,75.228,84.014,3pt,NaN,0,2
114,Adelaide 36ers,J. Randle,3,92.532,34.014,2pt,jumpshot,0,2
115,Adelaide 36ers,B. Teys,7,97.268,15.986,2pt,jumpshot,1,2
116,Adelaide 36ers,J. Randle,3,6.557,36.054,2pt,jumpshot,1,3
117,Adelaide 36ers,J. Randle,3,23.497,38.776,2pt,jumpshot,0,3
118,Adelaide 36ers,E. Jacobsen,11,5.647,50.000,2pt,tipin,1,3
119,Adelaide 36ers,D. Johnson,21,10.929,19.048,2pt,jumpshot,1,3
120,Adelaide 36ers,N. Sobey,20,6.193,54.082,2pt,jumpshot,0,3
121,Adelaide 36ers,N. Sobey,20,20.219,91.497,3pt,NaN,0,3
122,Adelaide 36ers,E. Jacobsen,11,7.104,52.721,2pt,layup,1,3
123,Adelaide 36ers,N. Sobey,20,7.468,50.000,2pt,dunk,1,3
124,Adelaide 36ers,J. Randle,3,30.965,60.204,3pt,NaN,1,3
125,Adelaide 36ers,N. Sobey,20,12.933,63.605,2pt,jumpshot,1,3
126,Adelaide 36ers,J. Randle,3,12.568,52.721,2pt,jumpshot,1,3
127,Adelaide 36ers,D. Johnson,21,7.468,47.279,2pt,jumpshot,1,3
128,Adelaide 36ers,D. Johnson,21,7.832,47.959,2pt,layup,1,3
129,Adelaide 36ers,J. Randle,3,10.565,21.088,2pt,jumpshot,0,4
130,Adelaide 36ers,M. Creek,55,28.962,30.952,3pt,NaN,0,4
131,Adelaide 36ers,J. Randle,3,32.605,45.578,3pt,NaN,1,4
132,Adelaide 36ers,B. Teys,7,24.226,71.769,2pt,jumpshot,1,4
133,Adelaide 36ers,M. Creek,55,6.557,47.619,2pt,jumpshot,0,4
134,Adelaide 36ers,J. Randle,3,16.758,94.218,3pt,NaN,1,4
135,Adelaide 36ers,N. Sobey,20,28.597,78.231,3pt,NaN,1,4
136,Adelaide 36ers,M. Creek,55,6.740,52.041,2pt,dunk,1,4
137,Adelaide 36ers,M. Creek,55,8.015,46.259,2pt,layup,1,4
138,Adelaide 36ers,E. Jacobsen,11,7.832,48.299,2pt,jumpshot,1,4
139,Adelaide 36ers,M. Creek,55,8.925,49.320,2pt,layup,1,4
140,Adelaide 36ers,J. Randle,3,23.679,64.626,2pt,jumpshot,0,4
141,Adelaide 36ers,J. Randle,3,8.197,45.238,2pt,jumpshot,0,4
142,Brisbane Bullets,D. Kickert,14,92.896,73.129,2pt,jumpshot,1,1
143,Brisbane Bullets,J. Beal,0,83.607,70.408,2pt,jumpshot,0,1
144,Brisbane Bullets,T. Craig,2,85.064,70.068,2pt,jumpshot,1,1
145,Brisbane Bullets,D. Kickert,14,90.528,65.646,2pt,jumpshot,1,1
146,Brisbane Bullets,T. Craig,2,93.260,61.905,2pt,layup,1,1
147,Brisbane Bullets,M. Young,3,90.346,54.082,2pt,jumpshot,0,1
148,Brisbane Bullets,T. Craig,2,65.392,58.163,3pt,NaN,0,1
149,Brisbane Bullets,T. Craig,2,94.536,22.449,2pt,jumpshot,0,1
150,Brisbane Bullets,D. Kickert,14,86.703,50.340,2pt,jumpshot,1,1
151,Brisbane Bullets,T. Craig,2,67.395,47.279,3pt,NaN,0,1
152,Brisbane Bullets,D. Kickert,14,64.845,56.463,3pt,NaN,1,1
153,Brisbane Bullets,T. Jervis,13,85.428,54.082,2pt,jumpshot,0,1
154,Brisbane Bullets,S. Bruce,9,91.621,40.476,2pt,layup,1,1
155,Brisbane Bullets,D. Kickert,14,88.707,46.939,2pt,jumpshot,1,1
156,Brisbane Bullets,T. Craig,2,83.971,75.170,2pt,jumpshot,0,1
157,Brisbane Bullets,J. Beal,0,86.339,45.238,2pt,jumpshot,0,1
158,Brisbane Bullets,J. Beal,0,90.710,63.605,2pt,jumpshot,0,1
159,Brisbane Bullets,T. Jervis,13,91.621,58.163,2pt,layup,1,1
160,NaN,I. Tueta,55,67.031,72.449,3pt,NaN,0,1
161,New Zealand Breakers,I. Tueta,55,67.031,72.449,3pt,NaN,0,1
162,Brisbane Bullets,I. Tueta,55,67.031,72.449,3pt,NaN,0,1
163,Brisbane Bullets,J. Beal,0,72.495,21.088,3pt,NaN,0,1
164,NaN,I. Tueta,55,77.049,70.748,2pt,jumpshot,0,2
165,New Zealand Breakers,I. Tueta,55,77.049,70.748,2pt,jumpshot,0,2
166,Brisbane Bullets,I. Tueta,55,77.049,70.748,2pt,jumpshot,0,2
167,Brisbane Bullets,J. Beal,0,70.674,65.646,3pt,NaN,1,2
168,Brisbane Bullets,S. Bruce,9,91.439,26.531,2pt,jumpshot,0,2
169,Brisbane Bullets,M. Young,3,87.796,52.041,2pt,jumpshot,0,2
170,Brisbane Bullets,M. Young,3,92.532,74.150,2pt,jumpshot,1,2
171,Brisbane Bullets,M. Young,3,89.617,43.197,2pt,layup,1,2
172,Brisbane Bullets,T. Craig,2,86.521,44.218,2pt,jumpshot,1,2
173,Brisbane Bullets,T. Craig,2,85.246,46.259,2pt,jumpshot,1,2
174,Brisbane Bullets,T. Craig,2,89.253,54.422,2pt,jumpshot,1,2
175,Brisbane Bullets,T. Craig,2,77.778,88.095,3pt,NaN,0,2
176,Brisbane Bullets,T. Jervis,13,89.617,47.619,2pt,jumpshot,1,2
177,Brisbane Bullets,T. Craig,2,84.882,54.762,2pt,jumpshot,0,2
178,NaN,I. Tueta,55,86.521,49.660,2pt,jumpshot,0,2
179,New Zealand Breakers,I. Tueta,55,86.521,49.660,2pt,jumpshot,0,2
180,Brisbane Bullets,I. Tueta,55,86.521,49.660,2pt,jumpshot,0,2
181,Brisbane Bullets,T. Jervis,13,94.171,50.000,2pt,tipin,0,2
182,Brisbane Bullets,T. Craig,2,94.171,50.000,2pt,tipin,1,2
183,Brisbane Bullets,S. Bruce,9,92.168,97.279,3pt,NaN,1,2
184,Brisbane Bullets,J. Beal,0,54.281,50.000,3pt,NaN,0,2
185,Brisbane Bullets,T. Craig,2,9.472,42.517,2pt,jumpshot,0,3
186,Brisbane Bullets,T. Craig,2,8.197,62.585,2pt,layup,1,3
187,Brisbane Bullets,J. Beal,0,10.565,59.864,2pt,jumpshot,0,3
188,Brisbane Bullets,J. Beal,0,25.865,16.667,3pt,NaN,0,3
189,Brisbane Bullets,T. Craig,2,24.044,48.639,2pt,jumpshot,0,3
190,Brisbane Bullets,D. Kickert,14,29.690,31.973,3pt,NaN,1,3
191,NaN,I. Tueta,55,7.650,35.714,2pt,jumpshot,0,3
192,New Zealand Breakers,I. Tueta,55,7.650,35.714,2pt,jumpshot,0,3
193,Brisbane Bullets,I. Tueta,55,7.650,35.714,2pt,jumpshot,0,3
194,Brisbane Bullets,T. Jervis,13,6.922,28.912,2pt,jumpshot,1,3
195,Brisbane Bullets,T. Jervis,13,10.565,45.578,2pt,jumpshot,1,3
196,Brisbane Bullets,T. Craig,2,6.011,30.952,2pt,jumpshot,0,3
197,Brisbane Bullets,R. TeRangi,25,28.780,76.190,3pt,NaN,0,3
198,Brisbane Bullets,J. Beal,0,8.379,36.735,2pt,jumpshot,0,3
199,NaN,I. Tueta,55,4.736,4.082,3pt,NaN,0,3
200,New Zealand Breakers,I. Tueta,55,4.736,4.082,3pt,NaN,0,3
201,Brisbane Bullets,I. Tueta,55,4.736,4.082,3pt,NaN,0,3
202,Brisbane Bullets,T. Craig,2,5.829,72.789,2pt,jumpshot,0,3
203,Brisbane Bullets,R. TeRangi,25,24.226,85.714,3pt,NaN,1,3
204,Brisbane Bullets,R. TeRangi,25,8.925,56.122,2pt,jumpshot,1,3
205,Brisbane Bullets,J. Kendle,20,48.998,83.673,3pt,NaN,0,3
206,Brisbane Bullets,S. Bruce,9,27.687,21.769,3pt,NaN,0,4
207,NaN,I. Tueta,55,24.772,14.966,3pt,NaN,0,4
208,New Zealand Breakers,I. Tueta,55,24.772,14.966,3pt,NaN,0,4
209,Brisbane Bullets,I. Tueta,55,24.772,14.966,3pt,NaN,0,4
210,Brisbane Bullets,D. Kickert,14,23.862,85.034,3pt,NaN,1,4
211,Brisbane Bullets,D. Kickert,14,7.468,65.986,2pt,jumpshot,1,4
212,Brisbane Bullets,J. Kendle,20,8.379,61.224,2pt,jumpshot,1,4
213,NaN,I. Tueta,55,16.576,57.483,2pt,jumpshot,0,4
214,New Zealand Breakers,I. Tueta,55,16.576,57.483,2pt,jumpshot,0,4
215,Brisbane Bullets,I. Tueta,55,16.576,57.483,2pt,jumpshot,0,4
216,Brisbane Bullets,J. Kendle,20,5.647,50.000,2pt,tipin,1,4
217,Brisbane Bullets,T. Craig,2,8.197,36.735,2pt,jumpshot,0,4
218,Brisbane Bullets,T. Craig,2,6.557,60.884,2pt,layup,1,4
219,Brisbane Bullets,D. Kickert,14,14.208,95.238,3pt,NaN,1,4
220,Brisbane Bullets,T. Jervis,13,6.922,40.816,2pt,jumpshot,0,4
221,Brisbane Bullets,S. Bruce,9,7.832,96.939,3pt,NaN,1,4
222,Brisbane Bullets,T. Jervis,13,8.743,59.864,2pt,jumpshot,1,4
223,Brisbane Bullets,S. Bruce,9,14.390,64.286,2pt,jumpshot,0,4
224,Brisbane Bullets,T. Craig,2,8.743,34.014,2pt,jumpshot,0,4
225,Brisbane Bullets,M. Young,3,20.219,8.163,3pt,NaN,0,4
226,New Zealand Breakers,P. Carter,1,22.769,61.224,2pt,jumpshot,0,1
227,New Zealand Breakers,K. Penney,6,28.780,28.231,3pt,NaN,1,1
228,New Zealand Breakers,K. Dillard,43,6.740,61.565,2pt,layup,1,1
229,New Zealand Breakers,K. Dillard,43,23.133,76.531,2pt,jumpshot,1,1
230,New Zealand Breakers,K. Penney,6,22.587,54.082,2pt,jumpshot,0,1
231,New Zealand Breakers,S. Ili,5,10.383,40.136,2pt,jumpshot,0,1
232,New Zealand Breakers,K. Penney,6,7.286,26.871,2pt,jumpshot,0,1
233,New Zealand Breakers,A. Pledger,35,6.740,36.735,2pt,jumpshot,0,1
234,New Zealand Breakers,K. Penney,6,27.322,83.333,3pt,NaN,0,1
235,New Zealand Breakers,A. Pledger,35,10.383,54.422,2pt,jumpshot,0,1
236,New Zealand Breakers,K. Dillard,43,24.226,66.327,2pt,jumpshot,0,1
237,New Zealand Breakers,A. Pledger,35,22.404,46.259,2pt,jumpshot,1,1
238,New Zealand Breakers,A. Pledger,35,20.219,49.660,2pt,jumpshot,0,1
239,New Zealand Breakers,P. Carter,1,33.151,51.361,3pt,NaN,0,2
240,New Zealand Breakers,A. Mitchell,25,9.107,55.782,2pt,dunk,1,2
241,New Zealand Breakers,F. Delany,3,13.297,3.741,3pt,NaN,1,2
242,New Zealand Breakers,S. Ili,5,26.047,22.109,3pt,NaN,1,2
243,New Zealand Breakers,A. Pledger,35,13.297,48.980,2pt,jumpshot,0,2
244,New Zealand Breakers,R. Loe,15,9.654,37.755,2pt,jumpshot,0,2
245,New Zealand Breakers,K. Dillard,43,23.679,11.905,3pt,NaN,0,2
246,New Zealand Breakers,R. Loe,15,24.408,82.653,3pt,NaN,0,2
247,New Zealand Breakers,M. Vukona,14,9.290,41.497,2pt,jumpshot,1,2
248,New Zealand Breakers,K. Penney,6,5.647,77.551,2pt,jumpshot,0,2
249,New Zealand Breakers,K. Dillard,43,10.383,43.878,2pt,layup,1,2
250,New Zealand Breakers,P. Carter,1,24.772,14.966,3pt,NaN,1,2
251,New Zealand Breakers,K. Dillard,43,14.390,58.163,2pt,jumpshot,1,2
252,New Zealand Breakers,K. Dillard,43,30.419,34.694,3pt,NaN,1,2
253,New Zealand Breakers,K. Penney,6,80.510,9.184,3pt,NaN,1,3
254,New Zealand Breakers,K. Dillard,43,80.146,46.939,2pt,jumpshot,0,3
255,New Zealand Breakers,R. Loe,15,89.617,55.782,2pt,jumpshot,1,3
256,New Zealand Breakers,K. Penney,6,86.339,48.980,2pt,jumpshot,1,3
257,New Zealand Breakers,K. Penney,6,91.621,3.401,3pt,NaN,0,3
258,New Zealand Breakers,P. Carter,1,71.403,79.932,3pt,NaN,0,3
259,New Zealand Breakers,A. Pledger,35,87.250,52.381,2pt,jumpshot,1,3
260,New Zealand Breakers,K. Dillard,43,89.800,39.456,2pt,jumpshot,0,3
261,New Zealand Breakers,A. Pledger,35,88.342,59.184,2pt,jumpshot,0,3
262,New Zealand Breakers,K. Dillard,43,84.882,65.986,2pt,jumpshot,1,3
263,New Zealand Breakers,A. Pledger,35,92.168,53.401,2pt,jumpshot,1,3
264,New Zealand Breakers,K. Dillard,43,68.488,27.551,3pt,NaN,0,3
265,New Zealand Breakers,K. Dillard,43,89.435,62.925,2pt,layup,1,3
266,New Zealand Breakers,K. Dillard,43,87.067,71.088,2pt,jumpshot,1,4
267,New Zealand Breakers,R. Loe,15,71.585,27.551,3pt,NaN,1,4
268,New Zealand Breakers,K. Dillard,43,92.896,39.796,2pt,jumpshot,1,4
269,New Zealand Breakers,K. Penney,6,67.213,55.442,3pt,NaN,1,4
270,New Zealand Breakers,K. Penney,6,74.681,84.354,3pt,NaN,0,4
271,New Zealand Breakers,K. Dillard,43,68.124,35.034,3pt,NaN,1,4
272,New Zealand Breakers,K. Dillard,43,75.956,87.755,3pt,NaN,0,4
273,New Zealand Breakers,F. Delany,3,70.310,25.510,3pt,NaN,1,4
274,New Zealand Breakers,K. Penney,6,90.528,65.306,2pt,jumpshot,0,4
275,New Zealand Breakers,K. Penney,6,71.949,79.932,3pt,NaN,1,4
276,New Zealand Breakers,A. Pledger,35,88.889,56.122,2pt,dunk,1,4
277,New Zealand Breakers,F. Delany,3,89.982,44.898,2pt,jumpshot,1,4
278,New Zealand Breakers,K. Dillard,43,91.075,46.599,2pt,layup,1,4
279,New Zealand Breakers,K. Dillard,43,74.317,14.286,3pt,NaN,0,4
280,New Zealand Breakers,K. Dillard,43,82.149,50.000,2pt,jumpshot,1,4
281,New Zealand Breakers,K. Penney,6,77.960,93.197,3pt,NaN,0,4
282,New Zealand Breakers,K. Dillard,43,76.867,56.122,2pt,jumpshot,1,4
283,Cairns Taipans,N. Jawai,15,76.685,69.728,2pt,jumpshot,0,1
284,Cairns Taipans,A. Loughton,40,67.577,58.163,3pt,NaN,0,1
285,Cairns Taipans,C. Gliddon,3,72.860,80.612,3pt,NaN,0,1
286,Cairns Taipans,F. Edwin,23,76.321,84.694,3pt,NaN,0,1
287,Cairns Taipans,N. Jawai,15,92.532,52.041,2pt,jumpshot,0,1
288,Cairns Taipans,T. Trice,0,91.985,20.748,2pt,jumpshot,1,1
289,Cairns Taipans,N. Egwu,21,92.532,25.170,2pt,jumpshot,1,1
290,Cairns Taipans,S. Weigh,13,68.306,55.782,3pt,NaN,1,1
291,Cairns Taipans,J. Weeks,97,96.903,39.456,2pt,layup,1,1
292,Cairns Taipans,J. Weeks,97,77.049,89.456,3pt,NaN,1,1
293,Cairns Taipans,N. Egwu,21,85.610,72.449,2pt,jumpshot,0,1
294,Cairns Taipans,T. Trice,0,91.985,46.939,2pt,layup,1,1
295,Cairns Taipans,S. Weigh,13,65.756,60.544,3pt,NaN,0,1
296,Cairns Taipans,N. Egwu,21,93.078,47.619,2pt,jumpshot,1,1
297,Cairns Taipans,A. Loughton,40,92.896,43.537,2pt,jumpshot,0,1
298,Cairns Taipans,D. Heuir,6,81.239,72.109,2pt,jumpshot,0,1
299,Cairns Taipans,M. McCarron,10,93.260,47.619,2pt,jumpshot,0,2
300,Cairns Taipans,D. Heuir,6,69.763,76.871,3pt,NaN,0,2
301,Cairns Taipans,A. Loughton,40,89.435,55.442,2pt,jumpshot,0,2
302,Cairns Taipans,N. Jawai,15,93.625,52.381,2pt,jumpshot,1,2
303,Cairns Taipans,T. Trice,0,83.607,24.490,2pt,jumpshot,0,2
304,Cairns Taipans,M. McCarron,10,92.896,58.163,2pt,jumpshot,0,2
305,Cairns Taipans,S. Weigh,13,92.896,13.605,2pt,jumpshot,0,2
306,Cairns Taipans,M. McCarron,10,94.171,45.238,2pt,jumpshot,0,2
307,Cairns Taipans,S. Weigh,13,85.428,51.361,2pt,jumpshot,0,2
308,Cairns Taipans,T. Trice,0,75.228,29.592,2pt,jumpshot,1,2
309,Cairns Taipans,T. Trice,0,93.260,52.721,2pt,layup,1,2
310,Cairns Taipans,M. McCarron,10,93.260,56.122,2pt,jumpshot,0,2
311,Cairns Taipans,N. Egwu,21,93.625,52.381,2pt,jumpshot,0,2
312,Cairns Taipans,J. Weeks,97,91.257,96.599,3pt,NaN,0,2
313,Cairns Taipans,N. Egwu,21,71.585,28.571,3pt,NaN,1,2
314,Cairns Taipans,F. Edwin,23,13.661,95.238,3pt,NaN,1,3
315,Cairns Taipans,C. Gliddon,3,11.111,4.082,3pt,NaN,0,3
316,Cairns Taipans,N. Jawai,15,7.286,51.361,2pt,jumpshot,0,3
317,Cairns Taipans,F. Edwin,23,5.647,50.000,2pt,tipin,1,3
318,Cairns Taipans,C. Gliddon,3,6.557,46.599,2pt,layup,1,3
319,Cairns Taipans,F. Edwin,23,27.140,21.769,3pt,NaN,1,3
320,Cairns Taipans,C. Gliddon,3,6.557,45.918,2pt,layup,1,3
321,Cairns Taipans,T. Trice,0,28.597,31.973,3pt,NaN,0,3
322,Cairns Taipans,S. Weigh,13,11.475,63.605,2pt,jumpshot,1,3
323,Cairns Taipans,A. Loughton,40,26.776,24.150,3pt,NaN,0,3
324,Cairns Taipans,S. Weigh,13,7.468,96.259,3pt,NaN,0,3

In [83]:
allshots.to_csv('/Users/ericnesi/Desktop/capstone_eric/datasets/allshots.csv')